# Generated by Django 5.1.1 on 2024-09-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionlevel',
            name='max_calories',
        ),
    ]
